# Generated by Django 6.0.3 on 2026-09-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response_source',
            field=models.CharField(default='fallback', max_length=20),
        ),
    ]
